In [2]:
##### Libraries

import json
import numpy as np
import os
import pandas as pd
import re
import sys
import fnmatch

import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import sklearn

%config InlineBackend.figure_format = 'png' #set 'png' here when working on notebook
%matplotlib inline

In [3]:
##### Setup

# Paths.

### directory path for Windows
#dir_path = r'C:\Users\Ryan\Dropbox\SPC\SPC_Python'

In [4]:
### directory path for OS
dir_path = r'/Users/owner/Dropbox/SPC/SPC_Python/NCPfiles'

In [5]:
ecm_files = os.listdir(dir_path)

In [6]:
# shell-style pattern in regular expression form used for re.match()
pattern = r'.*\.xlsm\Z'

In [7]:
for ecm_filename in ecm_files:
    # test whether filename string matches pattern string (*.xlsm)
    if fnmatch.fnmatch(ecm_filename, '*.xlsm'):
        print str(ecm_filename[:8])
        x = fnmatch.translate('*.xlsm')
        print x

NCP12032
.*\.xlsm\Z(?ms)
NCP12078
.*\.xlsm\Z(?ms)
NCP12093
.*\.xlsm\Z(?ms)
NCP12109
.*\.xlsm\Z(?ms)
NCP12113
.*\.xlsm\Z(?ms)
NCP12145
.*\.xlsm\Z(?ms)
NCP12146
.*\.xlsm\Z(?ms)
NCP12148
.*\.xlsm\Z(?ms)
NCP12237
.*\.xlsm\Z(?ms)
NCP12285
.*\.xlsm\Z(?ms)
NCP12285
.*\.xlsm\Z(?ms)
NCP12369
.*\.xlsm\Z(?ms)
NCP12404
.*\.xlsm\Z(?ms)
NCP12434
.*\.xlsm\Z(?ms)
NCP12441
.*\.xlsm\Z(?ms)
NCP12469
.*\.xlsm\Z(?ms)
NCP12473
.*\.xlsm\Z(?ms)
NCP12544
.*\.xlsm\Z(?ms)
NCP12616
.*\.xlsm\Z(?ms)
NCP12664
.*\.xlsm\Z(?ms)
NCP12669
.*\.xlsm\Z(?ms)
NCP12670
.*\.xlsm\Z(?ms)
NCP12708
.*\.xlsm\Z(?ms)
NCP12734
.*\.xlsm\Z(?ms)
NCP12768
.*\.xlsm\Z(?ms)
NCP12876
.*\.xlsm\Z(?ms)
NCP12987
.*\.xlsm\Z(?ms)
NCP13052
.*\.xlsm\Z(?ms)
NCP13053
.*\.xlsm\Z(?ms)
NCP13054
.*\.xlsm\Z(?ms)
NCP13073
.*\.xlsm\Z(?ms)
NCP13110
.*\.xlsm\Z(?ms)
NCP13195
.*\.xlsm\Z(?ms)
NCP13229
.*\.xlsm\Z(?ms)
NCP13244
.*\.xlsm\Z(?ms)

In [8]:
## Transform functions
def ecm_clean(df):
    df.dropna(1,'all', inplace=True)
    df.dropna(0,'any', inplace=True)

In [9]:
ecm = None
for ecm_filename in ecm_files:
    print ecm_filename
    if not re.match(pattern, ecm_filename):
        continue
    # Get NCP number
    ncp = str(ecm_filename[:8])
    # Get ecm data
    data = pd.read_excel(ecm_filename, 'Supplemental Tables', header=11, parse_cols="C:Q", skip_footer=80)
    # Clean data
    ecm_clean(data)
    # Add NCP number
    data['NCP'] = ncp
    # Get project details
    general = pd.read_excel(ecm_filename, 'General Info')
    ta = pd.read_excel(ecm_filename, 'Contacts')
    # Add project name, city, building type, TA, building area
    data['ProjName'] = str(general.iloc[3,7])
    data['City'] = str(general.iloc[6,7])
    data['BuildType'] = str(general.iloc[14,7])
    data['BuildArea'] = int(general.iloc[11,7])
    data['TA'] = str(ta.iloc[36,1])
    # Save
    if ecm is None:
        ecm = data
    else:
        ecm = ecm.append(data)

.DS_Store
.git
.ipynb_checkpoints
ComprehensiveProjectECM.csv
ECManalysisETL.ipynb
NCP12032 - 20 West 40th St - WB IncCalcv3.1.xlsm
NCP12078 - Inc Calc 3.1.xlsm
NCP12093 - 268 W St - Inc Calcv3.D_V.1.1 - TR Comments.xlsm
NCP12109 - Inctv.xlsm
NCP12113 - ACLS Vivarium - IncCalcv3.1.xlsm
NCP12145 - Inctv_1.xlsm
NCP12146 - Inctv.xlsm
NCP12148 - Inctv.xlsm
NCP12237 Inc Calc v3 D _v3.2.xlsm
NCP12285 - Hampton Bk Phase II -Inc Calc.xlsm
NCP12285 - Inctv.xlsm
NCP12369 - Inctv.xlsm
NCP12395 - 219 East 44th St - Inc Calc 1 8 Rev2.xlsx
NCP12404 WB Inc Calc v3.1.xlsm
NCP12434 - Inctv.xlsm
NCP12441 - Inctv.xlsm
NCP12443 - Inctv.xlsx
NCP12450 - Inctv.xlsx
NCP12469 - USTA Grandstand - WB Inc Calc v3.1.xlsm
NCP12473 - Fine Art Storage IncCalc v3.3.xlsm
NCP12544 - 425 Park Ave - Inc Calc v3.3_revcap.xlsm
NCP12616 - 55 Wythe St - IncCalc v3.1.xlsm
NCP12664 - River Campus -  Incentive Calc v3.D.2.xlsm
NCP12669 - L'Oreal HY - WB Incentive Calculator v3.2 D 20160609.xlsm
NCP12670-Meals on Wheels - Inc Calc v3.0_Rev2.xlsm
NCP12708 - Inctv.xlsm
NCP12734 - Lafayette Dev - WB Inc Calcv3.3.xlsm
NCP12768 - SAP - Inc Calc v3.2 .xlsm
NCP12876 WB Inc Calc v3.1.xlsm
NCP12987- WB IncCalc v3.2.xlsm
NCP13052 - Inctv.xlsm
NCP13053 - Inctv.xlsm
NCP13054 - Inctv.xlsm
NCP13073 - Inctv.xlsm
NCP13110 - Inctv.xlsm
NCP13195 - Inctv.xlsm
NCP13229 - Inctv.xlsm
NCP13244 - Inctv.xlsm
README.md

In [10]:
ecm.dtypes

BuildArea                                  int64
BuildType                                 object
City                                      object
Customer Summer Peak kW \nSavings        float64
Customer Winter Peak kW Savings          float64
DMP Summer Peak kW                       float64
DMP kW Incentive ($)                     float64
EEPS kWh Incentive ($)                   float64
Est. Savings Cost ($/yr)                 float64
Fossil Fuel\nSavings\n(MMBtu)            float64
Hide Column Q                            float64
Incremental Cost (Labor and Material)    float64
Measure Code                              object
Measure Description                       object
Measure Level TRC                        float64
Measure Level TRC w/ LEED                float64
Measure Life                             float64
NCP                                       object
NYSERDA\nIncentive\n($)                  float64
ProjName                                  object
Simple Payback Years (years)             float64
TA                                        object
Total MMBtu Savings                      float64
Yearly kWh Savings                       float64
dtype: object

In [11]:
## Add calculated fields, savings and $ per sf
ecm.drop('Hide Column Q', axis=1, inplace=True)
ecm = ecm.fillna(0)
ecm['Yearly kWh Savings_100sf']=ecm['Yearly kWh Savings']/ecm['BuildArea']*100
ecm['SumPeak_kW_100sf'] = ecm['Customer Summer Peak kW \nSavings']/ecm['BuildArea']*100
ecm['FossilFuel_MMBtu_100sf'] = ecm['Fossil Fuel\nSavings\n(MMBtu)']/ecm['BuildArea']*100
ecm['TotalSave_MMBTU_100sf'] = ecm['Total MMBtu Savings']/ecm['BuildArea']*100
ecm['YearSave_kWh_100sf'] = ecm['Yearly kWh Savings']/ecm['BuildArea']*100
ecm['Inctv_$_100sf'] = ecm['NYSERDA\nIncentive\n($)']/ecm['BuildArea']*100

In [12]:
## Check data quality
ecm.describe(percentiles=[0.25,0.5,0.75], include='all')

,BuildArea,BuildType,City,Customer Summer Peak kW Savings,Customer Winter Peak kW Savings,DMP Summer Peak kW,DMP kW Incentive ($),EEPS kWh Incentive ($),Est. Savings Cost ($/yr),Fossil Fuel Savings (MMBtu),...,Simple Payback Years (years),TA,Total MMBtu Savings,Yearly kWh Savings,Yearly kWh Savings_100sf,SumPeak_kW_100sf,FossilFuel_MMBtu_100sf,TotalSave_MMBTU_100sf,YearSave_kWh_100sf,Inctv_$_100sf
count,210.000000,210,210,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,...,210.000000,210,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
unique,NaN,19,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Office,New York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"EME Consulting Engineering, NYC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,32,153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,203201.485714,NaN,NaN,18.466022,-23.678034,4.199819,2895.192291,1667.484235,13043.174299,160.647519,...,11.673976,NaN,334.317054,50884.715714,38.195162,0.011825,0.138489,0.268849,38.195162,7.183967
std,188474.280881,NaN,NaN,55.001569,330.213738,21.084933,15585.409604,8044.095134,26240.565859,792.814230,...,24.427302,NaN,855.153261,119716.812705,80.066023,0.026425,0.550355,0.611101,80.066023,14.336581
min,13000.000000,NaN,NaN,-67.000000,-4697.300000,-10.590000,0.000000,0.000000,-94191.000000,-4116.400000,...,0.000000,NaN,-4481.335025,-607607.000000,-307.942405,-0.011780,-0.572021,-0.937082,-307.942405,0.000000
25%,78482.750000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,1288.750000,-29.850000,...,2.223930,NaN,27.456758,2094.750000,1.833378,0.000000,-0.019012,0.020683,1.833378,0.000000
50%,143000.000000,NaN,NaN,2.248000,0.891000,0.000000,0.000000,0.000000,5074.500000,0.000000,...,4.998006,NaN,107.590763,17082.000000,11.263088,0.001500,0.000000,0.089811,11.263088,0.411159
75%,241361.000000,NaN,NaN,12.232500,6.994675,0.000000,0.000000,0.000000,13560.000000,99.675000,...,10.913923,NaN,416.750209,64652.000000,47.735576,0.011334,0.097728,0.301173,47.735576,7.151709
max,760207.000000,NaN,NaN,487.410000,97.770000,210.450000,148932.905812,89529.280064,143582.000000,5570.000000,...,207.016997,NaN,5802.759774,686074.000000,444.353846,0.254348,4.312027,4.340439,444.353846,102.599138

In [13]:
## Check null values for each column
ecm.isnull().sum()

BuildArea                                0
BuildType                                0
City                                     0
Customer Summer Peak kW \nSavings        0
Customer Winter Peak kW Savings          0
DMP Summer Peak kW                       0
DMP kW Incentive ($)                     0
EEPS kWh Incentive ($)                   0
Est. Savings Cost ($/yr)                 0
Fossil Fuel\nSavings\n(MMBtu)            0
Incremental Cost (Labor and Material)    0
Measure Code                             0
Measure Description                      0
Measure Level TRC                        0
Measure Level TRC w/ LEED                0
Measure Life                             0
NCP                                      0
NYSERDA\nIncentive\n($)                  0
ProjName                                 0
Simple Payback Years (years)             0
TA                                       0
Total MMBtu Savings                      0
Yearly kWh Savings                       0
Yearly kWh Savings_100sf                 0
SumPeak_kW_100sf                         0
FossilFuel_MMBtu_100sf                   0
TotalSave_MMBTU_100sf                    0
YearSave_kWh_100sf                       0
Inctv_$_100sf                            0
dtype: int64

In [47]:
## Make consistent BuildType, City, 
ecm.groupby('TA').count()

,BuildArea,BuildType,City,Customer Summer Peak kW Savings,Customer Winter Peak kW Savings,DMP Summer Peak kW,DMP kW Incentive ($),EEPS kWh Incentive ($),Est. Savings Cost ($/yr),Fossil Fuel Savings (MMBtu),...,ProjName,Simple Payback Years (years),Total MMBtu Savings,Yearly kWh Savings,Yearly kWh Savings_100sf,SumPeak_kW_100sf,FossilFuel_MMBtu_100sf,TotalSave_MMBTU_100sf,YearSave_kWh_100sf,Inctv_$_100sf
TA,,,,,,,,,,,,,,,,,,,,,
"Ambrosino, DePinto & Schmieder",7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
Atelier Ten,31,31,31,31,31,31,31,31,31,31,...,31,31,31,31,31,31,31,31,31,31
"EME Consulting Engineering, NYC",57,57,57,57,57,57,57,57,57,57,...,57,57,57,57,57,57,57,57,57,57
L&S Energy Services,11,11,11,11,11,11,11,11,11,11,...,11,11,11,11,11,11,11,11,11,11
"Steven Winter Associates, Inc., NYC",22,22,22,22,22,22,22,22,22,22,...,22,22,22,22,22,22,22,22,22,22
"Vidaris, CT",20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
"Vidaris, NYC",43,43,43,43,43,43,43,43,43,43,...,43,43,43,43,43,43,43,43,43,43
WSP Flack + Kurtz,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,19,19

In [32]:
ecm['BuildType'].replace(['Classroom', 'Education - Elementary and Secondary', 'Elementary school', 'K through 12 School'],
                         'Education', inplace=True)

In [34]:
ecm['BuildType'].replace(['Multifamily Residential', 'Multifamily'], 'Residential', inplace=True)

In [36]:
ecm['BuildType'].replace('Research Laboratories', 'Laboratory', inplace=True)

In [42]:
ecm['BuildType'].replace('Commercial-Wholesale/Retail', 'Retail', inplace=True)

In [40]:
ecm['BuildType'].replace('Commercial Kitchen and Food Storage Facility', 'Restaurant', inplace=True)

In [45]:
ecm['City'].replace('New York, NY', 'New York', inplace=True)

In [50]:
# print to csv
ecm.to_csv('ComprehensiveProjectECM.csv')